# Generated by Django 5.2.6 on 2025-10-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        ('googledorks', '0002_entitytype_googledork_entity_placeholders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='googledorks.entity'),
        ),
        migrations.AlterField(
            model_name='chatfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('incorrect', 'Incorrect'), ('inappropriate', 'Inappropriate')], max_length=20),
        ),
    ]
