# Generated by Django 5.2.6 on 2025-10-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledorks', '0002_entitytype_googledork_entity_placeholders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledork',
            name='execution_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this dork has been executed'),
        ),
    ]
