# Generated by Django 5.2.6 on 2025-10-07 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledorks', '0003_googledork_execution_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('new_results', 'New Results Alert'), ('weekly_summary', 'Weekly Summary'), ('system_notification', 'System Notification'), ('test_email', 'Test Email')], max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField(help_text='HTML content with template variables')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this alert', max_length=200)),
                ('trigger_type', models.CharField(choices=[('new_results', 'New Results Found'), ('result_count_change', 'Result Count Changed'), ('keyword_found', 'Keyword Found in Results'), ('scheduled_report', 'Scheduled Report')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('condition_data', models.JSONField(blank=True, default=dict, help_text='Additional conditions for triggering (e.g., keywords, thresholds)')),
                ('send_email', models.BooleanField(default=True)),
                ('email_recipients', models.TextField(blank=True, default='', help_text='Comma-separated email addresses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('dork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='googledorks.googledork')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('result_count', models.IntegerField(default=0)),
                ('new_results_count', models.IntegerField(default=0)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_details', models.JSONField(blank=True, default=dict, help_text='Details about the notification (recipients, status, errors)')),
                ('result_summary', models.TextField(blank=True, help_text='Summary of results that triggered the alert')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='googledorks.alert')),
            ],
            options={
                'verbose_name': 'Alert History',
                'verbose_name_plural': 'Alert Histories',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomatedDork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('schedule_time', models.TimeField(help_text='Time of day to run (e.g., 09:00)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.IntegerField(default=0)),
                ('last_result_count', models.IntegerField(default=0)),
                ('send_email_on_completion', models.BooleanField(default=True)),
                ('email_recipients', models.TextField(blank=True, default='', help_text='Comma-separated email addresses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_dorks', to=settings.AUTH_USER_MODEL)),
                ('dork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='googledorks.googledork')),
            ],
            options={
                'verbose_name': 'Automated Dork',
                'verbose_name_plural': 'Automated Dorks',
                'ordering': ['-created_at'],
            },
        ),
    ]
