# Generated by Django 5.2.6 on 2025-10-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialcrawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawljob',
            name='target_username',
            field=models.CharField(blank=True, help_text='Username or handle to crawl', max_length=255),
        ),
    ]
