# Generated by Django 5.2.6 on 2025-10-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialcrawler', '0002_alter_crawljob_target_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='media_type',
            field=models.CharField(blank=True, default='', help_text='photo, video, carousel, etc.', max_length=50),
        ),
    ]
