# Generated by Django 5.2.6 on 2025-10-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialcrawler', '0003_add_default_to_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='banner_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='user_id',
            field=models.CharField(blank=True, default='', help_text='Platform-specific user ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
